jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Esegui scansione di sicurezza
        env:
          POLARIS_SERVER_URL: ${{ secrets.POLARIS_SERVER_URL }}
          COVERITY_URL: ${{ secrets.COVERITY_URL }}
          BLACKDUCKSCA_URL: ${{ secrets.BLACKDUCKSCA_URL }}
          SRM_URL: ${{ secrets.SRM_URL }}
        run: |
          if [ -z "$POLARIS_SERVER_URL" ] && [ -z "$COVERITY_URL" ] && [ -z "$BLACKDUCKSCA_URL" ] && [ -z "$SRM_URL" ]; then
            echo "Errore: almeno un URL di scansione deve essere specificato"
            exit 1
          fi
          echo "Scansione avviata..."

